import { useState, useMemo, useEffect, useRef } from "react";
import type { RunResult } from "../../../src/test-modes";
import type { Revision, Topic, DiscussionDepth } from "../../../src/types";
import { DEPTH_LABELS } from "../../../src/types";
import type { Metrics } from "../../../src/metrics";

// ─── Session 파일 형식 ────────────────────────────────────────────

interface Session {
  version:  "1";
  savedAt:  string;
  mode:     string;
  goals:    string[];
  summary: {
    revisionCount: number;
    decided:       number;
    undecided:     number;
    gptCalls:      number;
    claudeCalls:   number;
  };
  metrics:   Metrics;
  topics:    Topic[];
  revisions: Revision[];
  editLog?:  WsLogEntry[];
}

// ─── Workspace 타입 ───────────────────────────────────────────────

interface WsLogEntry {
  id: number;
  type: "file_edit_proposed" | "file_edit_applied";
  relativePath: string;
  summary: string;
  timestamp: string;
}

type DiffLine = { type: "same" | "add" | "remove"; text: string };

interface WsEditorState {
  workspacePath:   string | null;
  files:           string[];
  skipped:         number;
  selectedFile:    string | null;
  original:        string | null;
  proposed:        string | null;
  proposeSummary:  string;
  expandedFolders: Set<string>;
}

const WS_EDITOR_INITIAL: WsEditorState = {
  workspacePath:   null,
  files:           [],
  skipped:         0,
  selectedFile:    null,
  original:        null,
  proposed:        null,
  proposeSummary:  "",
  expandedFolders: new Set(),
};

type FileTreeNode =
  | { type: "folder"; name: string; path: string; children: FileTreeNode[] }
  | { type: "file";   name: string; path: string };

declare global {
  interface Window {
    api: {
      // Engine
      runMode:     (mode: string, dm: DiscussionMode)     => Promise<RunResult>;
      runCustom:   (goalText: string, dm: DiscussionMode) => Promise<RunResult>;
      runAll:      ()                 => Promise<RunResult[]>;
      saveSession: (json: string)     => Promise<{ canceled: boolean; filePath?: string }>;
      loadSession: () => Promise<
        | { ok: true;  content: string }
        | { ok: false; canceled?: boolean; error?: string }
      >;
      // Workspace
      selectWorkspace: () => Promise<
        | { canceled: true }
        | { canceled: false; workspacePath: string }
      >;
      scanWorkspace: (workspacePath: string) => Promise<{ files: string[]; skipped: number }>;
      readWorkspaceFile: (workspacePath: string, relativePath: string) => Promise<
        | { ok: true; content: string }
        | { ok: false; error: string }
      >;
      writeWorkspaceFile: (workspacePath: string, relativePath: string, content: string) => Promise<
        | { ok: true }
        | { ok: false; error: string }
      >;
      // Live Discussion
      startLiveDiscussion: (goals: string[], dm: DiscussionMode, depth: DiscussionDepth) => Promise<{ ok: boolean; error?: string }>;
      sendInterjection:    (message: string) => Promise<{ ok: boolean }>;
      acceptConsensus:     ()                     => Promise<{ ok: boolean }>;
      selectProposal:      (revisionId: number)  => Promise<{ ok: boolean }>;
      onDiscussionUpdate: (cb: (u: { history: Revision[]; topics: Topic[] }) => void) => () => void;
      onDiscussionStatus: (cb: (msg: string) => void) => () => void;
      onDiscussionDone:   (cb: (result: RunResult | null) => void) => () => void;
    };
  }
}

// ─── Mock 편집 로직 ───────────────────────────────────────────────

function mockEdit(
  relativePath: string,
  content: string,
): { result: string; summary: string } | { error: string } {
  const ext = relativePath.split(".").pop()?.toLowerCase() ?? "";
  const date = new Date().toISOString().slice(0, 10);

  if (["ts", "tsx", "js", "jsx"].includes(ext)) {
    const changes: string[] = [];
    let proposed = content;

    if (!proposed.startsWith("// [gcpt mock]")) {
      proposed = `// [gcpt mock] reviewed: ${date}\n` + proposed;
      changes.push("헤더 주석 추가");
    }

    const before = proposed;
    proposed = proposed.replace(/^(\s*)console\.log\(/gm, "$1// console.log(");
    if (proposed !== before) changes.push("console.log 주석 처리");

    if (!proposed.includes("// TODO:")) {
      proposed = proposed.trimEnd() + "\n// TODO: 코드 리뷰 후 확인하세요\n";
      changes.push("TODO 주석 추가");
    }

    return { result: proposed, summary: changes.join(", ") || "변경 없음" };
  }

  if (ext === "json") {
    try {
      const parsed = JSON.parse(content);
      const result = JSON.stringify(parsed, null, 2) + "\n";
      return { result, summary: result === content ? "변경 없음" : "JSON pretty formatting 적용" };
    } catch {
      return { error: "JSON 파싱 실패 — 수정 제안을 만들 수 없습니다" };
    }
  }

  if (ext === "md") {
    const changes: string[] = [];
    let proposed = content;

    if (!proposed.match(/^#\s+/m)) {
      proposed = `# 문서 제목\n\n${proposed}`;
      changes.push("제목 추가");
    }

    if (!proposed.includes("_Generated by gcpt mock editor_")) {
      proposed = proposed.trimEnd() + "\n\n---\n_Generated by gcpt mock editor_\n";
      changes.push("푸터 추가");
    }

    return { result: proposed, summary: changes.join(", ") || "변경 없음" };
  }

  if (ext === "css") {
    const changes: string[] = [];
    let proposed = content;

    if (!proposed.startsWith("/* [gcpt mock]")) {
      proposed = `/* [gcpt mock] reviewed: ${date} */\n` + proposed;
      changes.push("헤더 주석 추가");
    }

    if (!proposed.includes("/* TODO:")) {
      proposed = proposed.trimEnd() + "\n/* TODO: 미사용 스타일을 정리하세요 */\n";
      changes.push("TODO 주석 추가");
    }

    return { result: proposed, summary: changes.join(", ") || "변경 없음" };
  }

  if (ext === "html") {
    const normalized = content.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
    const header = `<!-- [gcpt mock] reviewed: ${date} -->`;
    if (normalized.startsWith("<!-- [gcpt mock] reviewed:")) {
      return { result: normalized, summary: "변경 없음" };
    }
    return { result: `${header}\n${normalized}`, summary: "헤더 주석 추가" };
  }

  return { result: content, summary: "지원되지 않는 파일 형식 — 변경 없음" };
}

// ─── Diff 계산 ────────────────────────────────────────────────────

const normalizeForDiff = (s: string) => s.replace(/\r\n/g, "\n").replace(/\r/g, "\n");

function lcsDiff(a: string[], b: string[]): DiffLine[] {
  const m = a.length, n = b.length;
  const dp = Array.from({ length: m + 1 }, () => new Array<number>(n + 1).fill(0));
  for (let i = 1; i <= m; i++)
    for (let j = 1; j <= n; j++)
      dp[i][j] = a[i-1] === b[j-1] ? dp[i-1][j-1] + 1 : Math.max(dp[i-1][j], dp[i][j-1]);

  const path: DiffLine[] = [];
  let i = m, j = n;
  while (i > 0 || j > 0) {
    if (i > 0 && j > 0 && a[i-1] === b[j-1]) {
      path.push({ type: "same",   text: a[i-1] }); i--; j--;
    } else if (j > 0 && (i === 0 || dp[i][j-1] >= dp[i-1][j])) {
      path.push({ type: "add",    text: b[j-1] }); j--;
    } else {
      path.push({ type: "remove", text: a[i-1] }); i--;
    }
  }
  return path.reverse();
}

function computeDiff(original: string, proposed: string): DiffLine[] {
  const oldNorm = normalizeForDiff(original);
  const newNorm = normalizeForDiff(proposed);
  const a = oldNorm.split("\n");
  const b = newNorm.split("\n");

  // LCS: max(m,n) ≤ 1200 — 1000줄 파일에 1~2줄 추가/삭제 케이스 포함 (1.44M ops, ~10ms)
  if (Math.max(a.length, b.length) <= 1200) return lcsDiff(a, b);

  // 초대형 파일 positional fallback (삽입/삭제가 없는 in-place 수정 전용)
  const result: DiffLine[] = [];
  const max = Math.max(a.length, b.length);
  for (let i = 0; i < max; i++) {
    if (i >= a.length)      result.push({ type: "add",    text: b[i] });
    else if (i >= b.length) result.push({ type: "remove", text: a[i] });
    else if (a[i] === b[i]) result.push({ type: "same",   text: a[i] });
    else { result.push({ type: "remove", text: a[i] }); result.push({ type: "add", text: b[i] }); }
  }
  return result;
}

// ─── File Tree ────────────────────────────────────────────────────

function buildTree(files: string[]): FileTreeNode[] {
  const root: FileTreeNode[] = [];
  const folderMap = new Map<string, FileTreeNode & { type: "folder" }>();

  for (const file of files) {
    const parts = file.split("/");
    let siblings = root;
    let cumPath = "";

    for (let i = 0; i < parts.length - 1; i++) {
      cumPath = cumPath ? `${cumPath}/${parts[i]}` : parts[i];
      if (!folderMap.has(cumPath)) {
        const node: FileTreeNode & { type: "folder" } = {
          type: "folder", name: parts[i], path: cumPath, children: [],
        };
        folderMap.set(cumPath, node);
        siblings.push(node);
      }
      siblings = folderMap.get(cumPath)!.children;
    }

    siblings.push({ type: "file", name: parts[parts.length - 1], path: file });
  }

  return root;
}

// ─── 상수 ─────────────────────────────────────────────────────────

const MODES = ["normal", "parsefail", "apierror", "delay", "mixed", "stress"];
const LS_KEY = "gcpt-ws-state";
const LS_VER = 2;

// Live mode 실행 시 모드별 기본 goal 목록
const GOAL_SETS: Record<string, string[]> = {
  normal:    ["데이터베이스 기술 스택 결정"],
  parsefail: ["프레임워크 선택"],
  apierror:  ["배포 전략 결정"],
  delay:     ["인증 방식 선택"],
  mixed:     ["상태 관리 라이브러리 선택"],
  stress:    ["데이터베이스 기술 스택 결정", "프레임워크 선택"],
};

// Actor 메타데이터 — label + color (새 actor 추가 시 여기만 수정)
const ACTOR_META: Record<string, { label: string; color: string }> = {
  user:   { label: "User",   color: "#858585" },
  gpt:    { label: "GPT",    color: "#4ec9b0" },
  claude: { label: "Claude", color: "#c586c0" },
  gemini: { label: "Gemini", color: "#f4a261" },
  system: { label: "System", color: "#6a9fb5" },
};
type PassMap = Record<string, "pass" | "fail" | null>;
type AppView = "engine" | "workspace";
type DiscussionMode = "general" | "development" | "idea";

const DISC_MODE_LABELS: Record<DiscussionMode, string> = {
  general:     "일반",
  development: "개발",
  idea:        "아이디어",
};

// ─── App ──────────────────────────────────────────────────────────

export default function App() {
  const [view,             setView]             = useState<AppView>("engine");
  const [selected,         setSelected]         = useState("normal");
  const [result,           setResult]           = useState<RunResult | null>(null);
  const [passMap,          setPassMap]          = useState<PassMap>({});
  const [running,          setRunning]          = useState(false);
  const [runLabel,         setRunLabel]         = useState("");
  const [selectedTopicIdx, setSelectedTopicIdx] = useState<number | null>(null);
  const [selectedRevId,    setSelectedRevId]    = useState<number | null>(null);
  const [customGoal,       setCustomGoal]       = useState("");
  const [sessionStatus,    setSessionStatus]    = useState<string>("");
  const [wsLog,   setWsLog]   = useState<WsLogEntry[]>([]);
  const [wsState, setWsState] = useState<WsEditorState>(WS_EDITOR_INITIAL);
  const wsLogId            = useRef(0);
  const initialSaveSkipped = useRef(false);

  // ── 토론 모드 / 깊이 ─────────────────────────────────────────────
  const [discussionMode,  setDiscussionMode]  = useState<DiscussionMode>("general");
  const [discussionDepth, setDiscussionDepth] = useState<DiscussionDepth>("balanced");

  // ── Live Discussion 상태 ─────────────────────────────────────────
  const [liveEnabled,    setLiveEnabled]    = useState(false); // 실행 방식 토글
  const [aiProcessing,   setAiProcessing]   = useState(false); // AI worker가 실제 연산 중인지
  const [liveResult,     setLiveResult]     = useState<RunResult | null>(null);
  const [liveStatus,     setLiveStatus]     = useState("");

  // live 세션 결과가 있으면 continuation 가능 (computed)
  const liveSessionActive = result?.mode === "live";

  function addWsLog(entry: Omit<WsLogEntry, "id">) {
    setWsLog(prev => [{ ...entry, id: ++wsLogId.current }, ...prev]);
  }

  function clearWsLog() {
    setWsLog([]);
    wsLogId.current = 0;
  }

  useEffect(() => {
    setSelectedTopicIdx(null);
    setSelectedRevId(null);
  }, [result]);

  // ── Live Discussion IPC 이벤트 구독 ─────────────────────────────
  useEffect(() => {
    const cleanUpdate = window.api.onDiscussionUpdate(({ history, topics }) => {
      console.log("[renderer] discussion:update history.length=", history.length);
      setLiveResult({
        mode:          "live",
        metrics:       { calls: { gpt: { total:0,parseOk:0,parseFail:0,apiError:0 }, claude: { total:0,parseOk:0,parseFail:0,apiError:0 }, gemini: { total:0,parseOk:0,parseFail:0,apiError:0 } }, latencyMs: [], tokens: { prompt:0,completion:0 }, topics: { decided:0,undecided:0 } },
        revisionCount: history.length,
        topics,
        history,
      });
    });
    const cleanStatus = window.api.onDiscussionStatus(msg => setLiveStatus(msg));

    // 토론 완료: 최종 결과(metrics 포함)로 교체 후 AI 처리 상태 해제
    const cleanDone = window.api.onDiscussionDone(finalResult => {
      console.log("[renderer] discussion:done", finalResult ? `revisionCount=${finalResult.revisionCount}` : "null");
      if (finalResult) setResult(finalResult);
      setAiProcessing(false); // AI 연산 완료
      setLiveResult(null);
      setLiveStatus("");
      // 빌드·상태 확인용 — 이 로그 이후 버튼이 여전히 잠겨 있으면 React DevTools로 상태를 확인
      console.log("[renderer state] after discussion:done", {
        // running: setAiProcessing(false) 호출 직전까지는 true — 이후 false
        liveSessionActive: finalResult?.mode === "live",
        executionRunning: "→ false (aiProcessing cleared above)",
      });
    });

    return () => { cleanUpdate(); cleanStatus(); cleanDone(); };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // ── localStorage 복원 (mount 1회) ───────────────────────────────
  useEffect(() => {
    try {
      const raw = localStorage.getItem(LS_KEY);
      console.log("[ws localStorage] restore raw", raw ? raw.slice(0, 300) : null);
      if (!raw) return;

      const saved = JSON.parse(raw);
      console.log("[ws localStorage] restore parsed version=", saved.version, "workspacePath=", saved.workspacePath, "selectedFile=", saved.selectedFile, "files.length=", saved.files?.length);

      if (saved.version !== LS_VER) {
        console.log("[ws localStorage] version mismatch (saved:", saved.version, "expected:", LS_VER, ") → clearing");
        localStorage.removeItem(LS_KEY);
        return;
      }

      const restored: WsEditorState = {
        workspacePath:   saved.workspacePath   ?? null,
        files:           Array.isArray(saved.files) ? saved.files : [],
        skipped:         saved.skipped         ?? 0,
        selectedFile:    saved.selectedFile    ?? null,
        original:        saved.original        ?? null,
        proposed:        null,    // 항상 초기화 (파일이 바뀌었을 수 있음)
        proposeSummary:  "",
        expandedFolders: new Set<string>(
          Array.isArray(saved.expandedFolders) ? saved.expandedFolders : [],
        ),
      };
      setWsState(restored);

      if (Array.isArray(saved.wsLog) && saved.wsLog.length > 0) {
        setWsLog(saved.wsLog as WsLogEntry[]);
        wsLogId.current = Math.max(...(saved.wsLog as WsLogEntry[]).map(e => e.id), 0);
      }

      // 선택 파일이 있으면 최신 내용으로 재취득
      console.log("[ws restore] selectedFile", restored.selectedFile);
      if (restored.workspacePath && restored.selectedFile) {
        window.api.readWorkspaceFile(restored.workspacePath, restored.selectedFile)
          .then(res => {
            console.log("[ws restore] reread ok=", res.ok);
            if (res.ok) {
              setWsState(prev => ({ ...prev, original: res.content.replace(/\r\n/g, "\n") }));
            } else {
              setWsState(prev => ({ ...prev, selectedFile: null, original: null }));
            }
          })
          .catch(e => {
            console.error("[ws restore] reread error", e);
            setWsState(prev => ({ ...prev, selectedFile: null, original: null }));
          });
      }
    } catch (e) {
      console.error("[ws localStorage] restore error", e);
      localStorage.removeItem(LS_KEY);
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // ── localStorage 저장 (wsState/wsLog 변경 시) ───────────────────
  // 첫 번째 실행은 반드시 건너뜀: restore effect가 같은 render pass에서 이미 실행됐으므로
  // wsState가 여전히 WS_EDITOR_INITIAL인 상태에서 저장하면 기존 데이터가 덮힘
  useEffect(() => {
    if (!initialSaveSkipped.current) {
      initialSaveSkipped.current = true;
      console.log("[ws localStorage] skipping initial save (wsState is still initial)");
      return;
    }
    try {
      const snapshot = {
        version:         LS_VER,
        workspacePath:   wsState.workspacePath,
        files:           wsState.files,
        skipped:         wsState.skipped,
        selectedFile:    wsState.selectedFile,
        original:        wsState.original,
        expandedFolders: Array.from(wsState.expandedFolders),
        wsLog,
      };
      console.log("[ws localStorage] save workspacePath=", snapshot.workspacePath, "selectedFile=", snapshot.selectedFile, "files.length=", snapshot.files.length);
      localStorage.setItem(LS_KEY, JSON.stringify(snapshot));
    } catch {
      // QuotaExceededError 등 무시
    }
  }, [wsState, wsLog]);

  const topicRevRanges = useMemo(() => {
    if (!result) return [];
    return result.topics.map((topic, i) => ({
      startId: topic.startRevId,
      endId:   i + 1 < result.topics.length ? result.topics[i + 1].startRevId : Infinity,
    }));
  }, [result]);

  const displayedRevisions = useMemo(() => {
    if (!result) return [];
    if (selectedTopicIdx === null) return result.history;
    const r = topicRevRanges[selectedTopicIdx];
    if (!r) return result.history;
    return result.history.filter(rev => rev.id >= r.startId && rev.id < r.endId);
  }, [result, selectedTopicIdx, topicRevRanges]);

  // revision id → Revision 조회 (ref 표시용)
  const revMap = useMemo(
    () => new Map((result?.history ?? []).map(r => [r.id, r])),
    [result],
  );

  function handleTopicClick(idx: number) {
    setSelectedTopicIdx(prev => prev === idx ? null : idx);
    setSelectedRevId(null);
  }

  function handleRevClick(revId: number) {
    setSelectedRevId(prev => prev === revId ? null : revId);
    const idx = topicRevRanges.findIndex(r => revId >= r.startId && revId < r.endId);
    setSelectedTopicIdx(idx >= 0 ? idx : null);
  }

  async function runSelected() {
    if (liveEnabled) {
      await startLiveRun(GOAL_SETS[selected] ?? ["데이터베이스 기술 스택 결정"], discussionMode);
    } else {
      setRunning(true);
      setRunLabel(`mock:${selected}`);
      const r = await window.api.runMode(selected, discussionMode);
      setResult(r);
      setRunning(false);
    }
  }

  async function runCustom() {
    const goal = customGoal.trim();
    if (!goal) return;
    if (liveEnabled) {
      setSelected("custom");
      await startLiveRun([goal], discussionMode);
    } else {
      setRunning(true);
      setRunLabel(`"${goal.slice(0, 20)}${goal.length > 20 ? "…" : ""}"`);
      setSelected("custom");
      const r = await window.api.runCustom(goal, discussionMode);
      setResult(r);
      setRunning(false);
    }
  }

  async function saveSession() {
    if (!result) return;
    const goals = result.history
      .filter(r => r.patch.payload.type === "set_goal")
      .map(r => (r.patch.payload as { goal: string }).goal);

    const session: Session = {
      version: "1",
      savedAt: new Date().toISOString(),
      mode:    result.mode,
      goals,
      summary: {
        revisionCount: result.revisionCount,
        decided:       result.metrics.topics.decided,
        undecided:     result.metrics.topics.undecided,
        gptCalls:      result.metrics.calls.gpt.total,
        claudeCalls:   result.metrics.calls.claude.total,
      },
      metrics:   result.metrics,
      topics:    result.topics,
      revisions: result.history,
      editLog:   wsLog.length > 0 ? wsLog : undefined,
    };

    const json = JSON.stringify(session, null, 2);
    const res  = await window.api.saveSession(json);
    if (!res.canceled && res.filePath) {
      const name = res.filePath.split(/[\\/]/).pop() ?? res.filePath;
      setSessionStatus(`저장됨: ${name}`);
      setTimeout(() => setSessionStatus(""), 4000);
    }
  }

  async function loadSession() {
    const showError = (msg: string) => {
      console.error("[renderer] loadSession:", msg);
      setSessionStatus(`오류: ${msg}`);
      setTimeout(() => setSessionStatus(""), 6000);
    };

    try {
      console.log("[renderer] loadSession: invoking IPC");
      const res = await window.api.loadSession();
      console.log("[renderer] loadSession: IPC returned, ok=", res.ok);

      if (!res.ok) {
        if (!res.canceled) showError(res.error ?? "파일 읽기 실패");
        return;
      }

      const { content } = res;
      let session: Session;
      try {
        session = JSON.parse(content) as Session;
      } catch {
        showError("JSON 파싱 실패 — 파일이 손상됐을 수 있습니다");
        return;
      }

      if (session.version !== "1") { showError(`지원하지 않는 버전: ${session.version}`); return; }
      if (!Array.isArray(session.revisions) || !Array.isArray(session.topics)) {
        showError("세션 구조 오류: revisions 또는 topics 필드 누락");
        return;
      }

      // 구 세션 파일에 gemini 필드가 없을 수 있으므로 패치
      const loadedMetrics = session.metrics;
      if (!loadedMetrics.calls.gemini) {
        loadedMetrics.calls.gemini = { total: 0, parseOk: 0, parseFail: 0, apiError: 0 };
      }

      const restored: RunResult = {
        mode:          session.mode,
        metrics:       loadedMetrics,
        revisionCount: session.summary.revisionCount,
        topics:        session.topics,
        history:       session.revisions,
      };

      setResult(restored);
      setSelected(session.mode === "custom" ? "custom" : session.mode);
      if (session.mode === "custom" && session.goals.length > 0)
        setCustomGoal(session.goals.join("\n"));
      if (Array.isArray(session.editLog) && session.editLog.length > 0) {
        setWsLog(session.editLog);
        wsLogId.current = Math.max(...session.editLog.map(e => e.id), 0);
      }

      const goalSummary = session.goals.slice(0, 2).join(", ") + (session.goals.length > 2 ? " …" : "");
      setSessionStatus(`불러옴: ${goalSummary}`);
      setTimeout(() => setSessionStatus(""), 4000);
      console.log("[renderer] loadSession: done");

    } catch (e) {
      showError(e instanceof Error ? e.message : String(e));
    }
  }

  async function runAll() {
    // Live ON 상태에서는 전체 테스트 미지원 (버튼이 비활성화되므로 도달하지 않음)
    if (liveEnabled) return;
    setRunning(true);
    setRunLabel("전체 테스트");
    const results = await window.api.runAll();
    const map: PassMap = {};
    for (const r of results) map[r.mode] = r.metrics.topics.undecided === 0 ? "pass" : "fail";
    setPassMap(map);
    setResult(results[results.length - 1]);
    setRunning(false);
  }

  // Live 버튼 — 실행 방식 토글만 담당 (실행 자체는 runSelected/runCustom에서 처리)
  function toggleLive() {
    setLiveEnabled(prev => !prev);
  }

  // Live 실행 — runSelected/runCustom에서 liveEnabled 시 호출
  async function startLiveRun(goals: string[], dm: DiscussionMode = discussionMode, depth: DiscussionDepth = discussionDepth) {
    console.log("[renderer] calling startLiveDiscussion", goals, "mode=", dm, "depth=", depth);
    try {
      setAiProcessing(true);
      setLiveResult(null);
      setLiveStatus("토론 시작 중...");
      setRunLabel("live");
      setSelectedTopicIdx(null);
      setSelectedRevId(null);

      const res = await window.api.startLiveDiscussion(goals, dm, depth);
      if (!res.ok) {
        console.error("[renderer] startLiveDiscussion failed:", res.error);
        setAiProcessing(false);
        setLiveStatus("");
      }
      // 완료/정리는 onDiscussionDone 핸들러에서 처리
    } catch (e) {
      console.error("[renderer] startLive error:", e);
      setAiProcessing(false);
      setLiveStatus("");
    }
  }

  // Manual 모드 — policy 최고 점수 자동 채택 (토론 중에도 호출 가능)
  async function handleAcceptConsensus() {
    const wasIdle = !aiProcessing;
    if (wasIdle) setAiProcessing(true);
    const res = await window.api.acceptConsensus();
    if (!res.ok) {
      console.warn("[renderer] acceptConsensus failed");
      if (wasIdle) setAiProcessing(false);
    }
  }

  // Manual 모드 — 특정 proposal 직접 채택 (토론 중에도 호출 가능)
  async function handleSelectProposal(revisionId: number) {
    const wasIdle = !aiProcessing;
    if (wasIdle) setAiProcessing(true);
    const res = await window.api.selectProposal(revisionId);
    if (!res.ok) {
      console.warn("[renderer] selectProposal failed revisionId=", revisionId);
      if (wasIdle) setAiProcessing(false);
    }
  }

  // interjection 전송 — 세션 활성 여부 확인 후 live view 재활성화
  async function handleInterjection(msg: string) {
    const res = await window.api.sendInterjection(msg);
    if (!res.ok) {
      console.warn("[renderer] interjection ignored — no active session");
      return;
    }
    // continuation view 활성화: 현재 result를 기준으로 live 업데이트 수신
    setLiveResult(result);
    setAiProcessing(true);
    setLiveStatus("토론 재개 중...");
  }

  // AI 처리 중: liveResult (실시간) / idle: result (최종 스냅샷)
  // aiProcessing 중에 liveResult가 null이면 result로 fallback (초기 로딩 공백 방지)
  const displayResult = aiProcessing ? (liveResult ?? result) : result;

  return (
    <div className="app">
      <Header
        view={view}
        onViewChange={setView}
        executionRunning={running || aiProcessing}
        liveSessionActive={liveSessionActive}
        liveStatus={liveStatus}
        label={runLabel}
        onRun={runSelected}
        onRunAll={runAll}
        liveEnabled={liveEnabled}
        onToggleLive={toggleLive}
        canSave={!!result}
        onSave={saveSession}
        onLoad={loadSession}
        sessionStatus={sessionStatus}
      />
      {view === "engine" ? (
        <>
          <div className="body">
            <Sidebar
              modes={MODES}
              selected={selected}
              passMap={passMap}
              onSelect={setSelected}
              customGoal={customGoal}
              onCustomGoalChange={setCustomGoal}
              onCustomRun={runCustom}
              running={running || aiProcessing}
              discussionMode={discussionMode}
              onDiscussionModeChange={setDiscussionMode}
              discussionDepth={discussionDepth}
              onDiscussionDepthChange={setDiscussionDepth}
            />
            <div className="panels">
              <TopicPanel
                result={displayResult}
                selectedTopicIdx={selectedTopicIdx}
                onTopicClick={handleTopicClick}
              />
              <DiscussionPanel
                result={displayResult}
                selectedTopicIdx={selectedTopicIdx}
                liveStatus={liveStatus}
                liveRunning={aiProcessing}
                isLiveSession={liveSessionActive}
                onInterjection={handleInterjection}
                isManualMode={discussionDepth === "manual"}
                onAcceptConsensus={handleAcceptConsensus}
                onSelectProposal={handleSelectProposal}
              />
              <TimelinePanel
                revisions={aiProcessing ? (liveResult?.history ?? []) : displayedRevisions}
                totalCount={displayResult?.revisionCount ?? 0}
                isFiltered={!aiProcessing && selectedTopicIdx !== null}
                selectedRevId={selectedRevId}
                onRevClick={handleRevClick}
                wsLog={wsLog}
                revMap={revMap}
              />
            </div>
          </div>
          <MetricsBar result={displayResult} />
        </>
      ) : (
        <WorkspaceEditor
          wsState={wsState}
          setWsState={setWsState}
          wsLog={wsLog}
          addWsLog={addWsLog}
          clearWsLog={clearWsLog}
        />
      )}
    </div>
  );
}

// ─── Header ──────────────────────────────────────────────────────

function Header({ view, onViewChange, executionRunning, liveSessionActive, liveStatus, label,
                  onRun, onRunAll, liveEnabled, onToggleLive,
                  canSave, onSave, onLoad, sessionStatus }: {
  view: AppView; onViewChange: (v: AppView) => void;
  executionRunning: boolean;   // AI가 실제 연산 중 — 버튼 잠금 기준
  liveSessionActive: boolean;  // live 세션 결과 존재 — continuation 가능
  liveStatus: string;          // 오케스트레이터 상태 메시지
  label: string;
  onRun: () => void; onRunAll: () => void;
  liveEnabled: boolean; onToggleLive: () => void;
  canSave: boolean; onSave: () => void; onLoad: () => void;
  sessionStatus: string;
}) {
  // 상태 텍스트: 3단계 (연산 중 / 세션 idle / 일반)
  const statusText = executionRunning
    ? `● ${liveStatus || `AI discussing... ${label}`}`
    : liveSessionActive
    ? "● Live session active"
    : sessionStatus
    ? sessionStatus
    : view === "engine" && label
    ? `완료: ${label}`
    : "대기 중";

  const statusClass = executionRunning
    ? "running"
    : liveSessionActive
    ? "live-idle"
    : sessionStatus
    ? "session-msg"
    : "";

  return (
    <div className="header">
      <h1>gcpt</h1>
      <div className="view-tabs">
        <button
          className={`view-tab ${view === "engine" ? "active" : ""}`}
          onClick={() => onViewChange("engine")}
        >Revision Engine</button>
        <button
          className={`view-tab ${view === "workspace" ? "active" : ""}`}
          onClick={() => onViewChange("workspace")}
        >Workspace Editor</button>
      </div>
      {view === "engine" && (
        <>
          {/* 실행/전체테스트: AI 연산 중에만 잠금 */}
          <button className="primary" onClick={onRun} disabled={executionRunning}>▶ 실행</button>
          <button
            className={`live-btn ${liveEnabled ? "active" : ""}`}
            onClick={onToggleLive}
            disabled={executionRunning}
            title={liveEnabled ? "Live OFF — 클릭하면 일반 모드로 전환" : "Live ON — 클릭하면 실시간 토론 모드로 전환"}
          >
            {liveEnabled ? "⚡ Live ON" : "⚡ Live OFF"}
          </button>
          <button
            onClick={onRunAll}
            disabled={executionRunning || liveEnabled}
            title={liveEnabled ? "전체 테스트는 Live 모드 미지원" : ""}
          >전체 테스트</button>
          <div className="header-sep" />
          {/* 저장/불러오기: AI 연산 중에만 잠금 (continuation idle에서는 사용 가능) */}
          <button onClick={onSave} disabled={executionRunning || !canSave} title="세션 저장 (JSON)">저장</button>
          <button onClick={onLoad} disabled={executionRunning} title="세션 불러오기">불러오기</button>
        </>
      )}
      <span className={`status ${statusClass}`}>{statusText}</span>
    </div>
  );
}

// ─── Sidebar ─────────────────────────────────────────────────────

function Sidebar({ modes, selected, passMap, onSelect,
                   customGoal, onCustomGoalChange, onCustomRun, running,
                   discussionMode, onDiscussionModeChange,
                   discussionDepth, onDiscussionDepthChange }: {
  modes: string[]; selected: string; passMap: PassMap;
  onSelect: (m: string) => void;
  customGoal: string; onCustomGoalChange: (v: string) => void;
  onCustomRun: () => void; running: boolean;
  discussionMode: DiscussionMode; onDiscussionModeChange: (m: DiscussionMode) => void;
  discussionDepth: DiscussionDepth; onDiscussionDepthChange: (d: DiscussionDepth) => void;
}) {
  return (
    <div className="sidebar">
      <div className="sidebar-modes">
        <div className="sidebar-title">Mock Mode</div>
        {modes.map((m) => (
          <div
            key={m}
            className={`mode-item ${m === selected ? "active" : ""}`}
            onClick={() => onSelect(m)}
          >
            <span className={`mode-dot ${passMap[m] ?? ""}`} />
            mock:{m}
          </div>
        ))}
      </div>
      <div className="disc-mode-section">
        <div className="sidebar-title">토론 모드</div>
        <div className="disc-mode-btns">
          {(["general", "development", "idea"] as const).map(m => (
            <button
              key={m}
              className={`disc-mode-btn ${discussionMode === m ? "active" : ""}`}
              onClick={() => onDiscussionModeChange(m)}
              disabled={running}
              title={m === "general" ? "일상적인 주제, 단순 응답" : m === "development" ? "기술 스택·아키텍처 중심" : "창의적 제안·아이디어 발산"}
            >
              {DISC_MODE_LABELS[m]}
            </button>
          ))}
        </div>
      </div>
      <div className="disc-mode-section">
        <div className="sidebar-title">
          토론 깊이
          {discussionDepth === "deep" && <span className="depth-cost-hint"> ⚠ 토큰 증가</span>}
          {discussionDepth === "manual" && <span className="depth-cost-hint"> ⚠ 수동 종료</span>}
        </div>
        <div className="disc-mode-btns">
          {(["fast", "balanced", "deep", "manual"] as const).map(d => (
            <button
              key={d}
              className={`disc-mode-btn ${discussionDepth === d ? "active" : ""}`}
              onClick={() => onDiscussionDepthChange(d)}
              disabled={running}
              title={
                d === "fast"     ? "1라운드 · 빠른 결론" :
                d === "balanced" ? "2라운드 · 기본 (현재)" :
                d === "deep"     ? "5라운드 · 심층 토론 · 토큰 증가" :
                                   "5라운드 · 자동 수렴 없음 · 직접 결론 확정"
              }
            >
              {DEPTH_LABELS[d]}
            </button>
          ))}
        </div>
      </div>
      <div className="custom-goal-section">
        <div className="sidebar-title" style={{ padding: "8px 10px 6px" }}>직접 입력</div>
        <input
          className="custom-goal-input"
          type="text"
          placeholder="결정할 주제를 입력하세요"
          value={customGoal}
          onChange={e => onCustomGoalChange(e.target.value)}
          onKeyDown={e => e.key === "Enter" && !running && onCustomRun()}
          disabled={running}
        />
        <button
          className={`custom-goal-btn ${selected === "custom" ? "active" : ""}`}
          onClick={onCustomRun}
          disabled={running || !customGoal.trim()}
        >
          ▶ 토론 시작
        </button>
        {selected === "custom" && (
          <div className="custom-goal-hint">마지막 실행: 커스텀 모드</div>
        )}
      </div>
    </div>
  );
}

// ─── Topic Panel ─────────────────────────────────────────────────

function TopicPanel({ result, selectedTopicIdx, onTopicClick }: {
  result: RunResult | null;
  selectedTopicIdx: number | null;
  onTopicClick: (idx: number) => void;
}) {
  const hint = selectedTopicIdx !== null
    ? "클릭하여 필터 해제"
    : result ? "Topic 클릭 → Timeline 필터링" : "";

  return (
    <div className="panel">
      <div className="panel-title">
        Topic View
        {hint && <span className="panel-hint">{hint}</span>}
      </div>
      <div className="panel-body">
        {!result ? (
          <div className="empty">모드 선택 후 실행하세요</div>
        ) : result.topics.map((topic, i) => (
          <TopicCard
            key={i}
            topic={topic}
            isSelected={selectedTopicIdx === i}
            onClick={() => onTopicClick(i)}
          />
        ))}
      </div>
    </div>
  );
}

function TopicCard({ topic, isSelected, onClick }: {
  topic: Topic; isSelected: boolean; onClick: () => void;
}) {
  const isUndecided = topic.selectedOption === null && topic.status !== "reopened";

  return (
    <div
      className={`topic-card ${isSelected ? "selected" : ""} ${isUndecided ? "undecided" : ""}`}
      onClick={onClick}
    >
      <div className="topic-header">
        <span className="topic-goal">{topic.goal}</span>
        <span className={`badge ${topic.status}`}>{topic.status}</span>
        {topic.mode && topic.mode !== "general" && (
          <span className={`topic-mode-badge mode-${topic.mode}`}>
            {DISC_MODE_LABELS[topic.mode]}
          </span>
        )}
      </div>
      {topic.selectedOption && (
        <div className="topic-selected">
          ✓ {(topic.selectedOption.content as { value: string }).value}
          <span className="topic-selected-by">by {topic.selectedOption.selectedBy}</span>
        </div>
      )}
      {isUndecided && topic.status !== "decided" && (
        <div className="topic-undecided-label">⚠ 미결정</div>
      )}
      <div className="proposals">
        {topic.proposals.map((p, j) => {
          const c = p.content as { value: string; reason: string };
          return (
            <div key={j}>
              <div className="proposal-row">
                <span className="proposal-author">[{p.author}]</span>
                <span className="proposal-value">{c.value}</span>
                <span className="proposal-reason">— {c.reason}</span>
              </div>
              {p.rationale && <div className="proposal-rationale">↳ {p.rationale}</div>}
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ─── Timeline Panel ───────────────────────────────────────────────

function TimelinePanel({ revisions, totalCount, isFiltered, selectedRevId, onRevClick, wsLog, revMap }: {
  revisions: Revision[]; totalCount: number;
  isFiltered: boolean; selectedRevId: number | null;
  onRevClick: (id: number) => void;
  wsLog?: WsLogEntry[];
  revMap?: Map<number, Revision>;
}) {
  const title = isFiltered
    ? `Revision Timeline (${revisions.length} / ${totalCount} filtered)`
    : `Revision Timeline (${totalCount})`;

  return (
    <div className="panel">
      <div className="panel-title">
        {title}
        {isFiltered && <span className="panel-filter-badge">필터 중</span>}
      </div>
      <div className="panel-body" style={{ padding: 0 }}>
        {revisions.length === 0 ? (
          <div className="empty">—</div>
        ) : revisions.map((rev) => (
          <RevisionRow
            key={rev.id}
            rev={rev}
            isSelected={selectedRevId === rev.id}
            onClick={() => onRevClick(rev.id)}
            revMap={revMap}
          />
        ))}
        {wsLog && wsLog.length > 0 && (
          <>
            <div className="timeline-ws-sep">— File Edits ({wsLog.length}) —</div>
            {wsLog.map(entry => (
              <WsLogRow key={entry.id} entry={entry} />
            ))}
          </>
        )}
      </div>
    </div>
  );
}

// ─── AI Discussion Panel ──────────────────────────────────────────

function DiscussionPanel({ result, selectedTopicIdx, liveStatus, liveRunning, isLiveSession,
                           onInterjection, isManualMode, onAcceptConsensus, onSelectProposal }: {
  result: RunResult | null;
  selectedTopicIdx: number | null;
  liveStatus?: string;
  liveRunning?: boolean;
  isLiveSession?: boolean;
  onInterjection?: (msg: string) => void;
  isManualMode?: boolean;
  onAcceptConsensus?: () => void;
  onSelectProposal?: (revisionId: number) => void;
}) {
  const [interjectText, setInterjectText] = useState("");

  // Live 모드: 전체 history의 proposals 표시
  // 배치 모드: 선택된 topic의 proposals 표시
  const DISC_TYPES = new Set([
    "propose_decision", "propose_alternative", "consensus_reached", "user_interjection",
  ]);

  const msgs = useMemo(() => {
    if (!result) return [];
    if (liveRunning || isLiveSession) {
      return result.history.filter(r => DISC_TYPES.has(r.patch.payload.type));
    }
    if (selectedTopicIdx === null) return [];
    const topic  = result.topics[selectedTopicIdx];
    if (!topic) return [];
    const nextStart = result.topics[selectedTopicIdx + 1]?.startRevId ?? Infinity;
    return result.history.filter(
      r => r.id >= topic.startRevId && r.id < nextStart && DISC_TYPES.has(r.patch.payload.type),
    );
  }, [result, selectedTopicIdx, liveRunning]);

  // decided 값 추출 (입력창 안내 문구용)
  const decidedValue = msgs.find(r => r.patch.payload.type === "consensus_reached" || r.patch.payload.type === "select_option")
    ? (msgs.find(r => r.patch.payload.type === "consensus_reached" || r.patch.payload.type === "select_option")!
        .patch.payload as { selected?: string; value?: string }).selected
      ?? (msgs.find(r => r.patch.payload.type === "consensus_reached" || r.patch.payload.type === "select_option")!
        .patch.payload as { selected?: string; value?: string }).value
      ?? null
    : null;

  const hint = liveRunning
    ? "토론 진행 중..."
    : selectedTopicIdx !== null && result
    ? `Topic: ${result.topics[selectedTopicIdx]?.goal ?? ""}`
    : "Topic을 선택하면 토론 흐름이 표시됩니다";

  // 입력창 표시 조건: live 진행 중 OR 이전 live 세션 결과 있음
  const showInput = !!(liveRunning || isLiveSession);

  // Manual 모드: 특정 revision이 속한 topic의 활성 여부 확인 (채택 버튼 표시 조건)
  function isRevTopicActive(revId: number): boolean {
    if (!result) return false;
    for (let i = result.topics.length - 1; i >= 0; i--) {
      const nextStart = result.topics[i + 1]?.startRevId ?? Infinity;
      if (revId >= result.topics[i].startRevId && revId < nextStart) {
        const s = result.topics[i].status;
        return s === "active" || s === "reopened";
      }
    }
    return false;
  }

  function sendInterjection() {
    const msg = interjectText.trim();
    if (!msg || !onInterjection) return;
    onInterjection(msg);
    setInterjectText("");
  }

  return (
    <div className="panel discussion-panel">
      <div className="panel-title">
        AI Discussion
        {msgs.length > 0 && <span className="panel-hint">{msgs.length}개 발언</span>}
        {liveStatus && <span className="disc-live-status">{liveStatus}</span>}
      </div>
      <div className="panel-body discussion-body">
        {msgs.length === 0 ? (
          <div className="empty">{hint}</div>
        ) : msgs.map(rev => {
          const p    = rev.patch.payload as unknown as Record<string, unknown>;
          const meta = ACTOR_META[rev.author] ?? { label: rev.author, color: "#858585" };
          const t    = rev.patch.payload.type;
          const isConsensus    = t === "consensus_reached";
          const isInterjection = t === "user_interjection";
          const isCounter      = t === "propose_alternative";

          const badgeLabel =
            isConsensus    ? "자동 수렴" :
            isInterjection ? "의견"     :
            isCounter      ? "반박"     : "제안";

          const displayValue =
            isInterjection ? (p.message as string ?? "") :
            isConsensus    ? (p.selected as string ?? "") :
                             (p.value    as string ?? "");

          const displayReason = isConsensus
            ? `결정: ${p.winner ?? ""}`
            : (!isInterjection ? (p.reason as string ?? "") : "");

          // Manual 모드: proposal이고 해당 topic이 아직 미결정일 때만 채택 버튼 표시
          const showSelectBtn =
            isManualMode && !isConsensus && !isInterjection &&
            isRevTopicActive(rev.id) && !!onSelectProposal;

          return (
            <div
              key={rev.id}
              className={`disc-msg${isConsensus ? " disc-consensus" : ""}${isInterjection ? " disc-interjection" : ""}`}
            >
              <div className="disc-header">
                <span className="disc-actor" style={{ color: meta.color }}>{meta.label}</span>
                <span className={`disc-badge${isConsensus ? " consensus" : ""}${isInterjection ? " interjection" : ""}`}>
                  {badgeLabel}
                </span>
                {showSelectBtn && (
                  <button
                    className="disc-select-btn"
                    onClick={() => onSelectProposal!(rev.id)}
                    title={`이 제안을 채택합니다: ${displayValue}`}
                  >
                    채택
                  </button>
                )}
              </div>
              <div className="disc-value">{displayValue}</div>
              {displayReason && <div className="disc-reason">{displayReason}</div>}
            </div>
          );
        })}
      </div>
      {showInput && (
        <div className="disc-interject-area">
          {/* decided 이후 continuation 안내 */}
          {isLiveSession && !liveRunning && decidedValue && (
            <div className="disc-decided-hint">
              ✔ 현재 결론: <strong>{decidedValue}</strong>
              <span className="disc-decided-hint-sub"> — 추가 의견을 입력하면 토론이 다시 열립니다</span>
            </div>
          )}
          <div className="disc-interject">
            <input
              className="disc-interject-input"
              placeholder={liveRunning ? "의견 입력 (예: 비용보다 유지보수 우선)" : "추가 의견 / 재토론 주제 입력..."}
              value={interjectText}
              onChange={e => setInterjectText(e.target.value)}
              onKeyDown={e => e.key === "Enter" && !liveRunning && sendInterjection()}
              disabled={liveRunning} // AI가 응답 중일 때는 입력 비활성화
            />
            <button
              className="disc-interject-btn"
              onClick={sendInterjection}
              disabled={!interjectText.trim() || liveRunning}
            >
              {liveRunning ? "..." : "보내기"}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

function WsLogRow({ entry }: { entry: WsLogEntry }) {
  const isApplied = entry.type === "file_edit_applied";
  return (
    <div className="rev-row ws-edit-row">
      <span className="rev-id">ws</span>
      <span className={`rev-author ${isApplied ? "claude" : "gpt"}`}>
        {isApplied ? "applied" : "proposed"}
      </span>
      <div className="rev-content">
        <span className="rev-type">{entry.type}</span>
        <span className="rev-value">{entry.relativePath}</span>
        {entry.summary && <span className="rev-rat">{entry.summary}</span>}
      </div>
    </div>
  );
}

function RevisionRow({ rev, isSelected, onClick, revMap }: {
  rev: Revision; isSelected: boolean; onClick: () => void;
  revMap?: Map<number, Revision>;
}) {
  const p = rev.patch;
  const payload = p.payload as unknown as Record<string, unknown>;
  const value = (payload.value ?? payload.goal ?? payload.selected ?? payload.message ?? "") as string;
  const meta = ACTOR_META[rev.author] ?? { label: rev.author, color: "#858585" };

  // 반박 대상: refs[0]의 author를 표시
  const replyToRev = p.references?.[0] != null ? revMap?.get(p.references[0]) : undefined;
  const replyMeta  = replyToRev ? (ACTOR_META[replyToRev.author] ?? { label: replyToRev.author, color: "#858585" }) : null;

  return (
    <div className={`rev-row ${isSelected ? "selected" : ""}`} onClick={onClick}>
      <span className="rev-id">#{rev.id}</span>
      <span className="rev-author" style={{ color: meta.color }}>{meta.label}</span>
      <div className="rev-content">
        {replyMeta && (
          <span className="rev-reply">↩ <span style={{ color: replyMeta.color }}>{replyMeta.label}</span></span>
        )}
        <span className={`rev-type${p.type === "consensus_reached" ? " consensus" : p.type === "user_interjection" ? " interjection" : ""}`}>
          {p.type}
        </span>
        {value && <span className="rev-value">{value}</span>}
        {p.rationale && <span className="rev-rat">{p.rationale}</span>}
      </div>
    </div>
  );
}

// ─── Metrics Bar ─────────────────────────────────────────────────

function MetricsBar({ result }: { result: RunResult | null }) {
  const m = result?.metrics;
  const lat = m?.latencyMs ?? [];
  const avg = lat.length ? Math.round(lat.reduce((a, b) => a + b, 0) / lat.length) : 0;
  const max = lat.length ? Math.max(...lat) : 0;

  return (
    <div className="metrics">
      <MetricGroup label="GPT">
        <MetricItem name="calls"     value={m?.calls.gpt.total     ?? 0} />
        <MetricItem name="ok"        value={m?.calls.gpt.parseOk   ?? 0} accent="ok" />
        <MetricItem name="parseFail" value={m?.calls.gpt.parseFail ?? 0} accent={(m?.calls.gpt.parseFail ?? 0) > 0 ? "warn" : undefined} />
        <MetricItem name="apiErr"    value={m?.calls.gpt.apiError  ?? 0} accent={(m?.calls.gpt.apiError  ?? 0) > 0 ? "err"  : undefined} />
      </MetricGroup>
      <div className="metrics-sep" />
      <MetricGroup label="Claude">
        <MetricItem name="calls"     value={m?.calls.claude.total     ?? 0} />
        <MetricItem name="ok"        value={m?.calls.claude.parseOk   ?? 0} accent="ok" />
        <MetricItem name="parseFail" value={m?.calls.claude.parseFail ?? 0} accent={(m?.calls.claude.parseFail ?? 0) > 0 ? "warn" : undefined} />
        <MetricItem name="apiErr"    value={m?.calls.claude.apiError  ?? 0} accent={(m?.calls.claude.apiError  ?? 0) > 0 ? "err"  : undefined} />
      </MetricGroup>
      {(m?.calls.gemini?.total ?? 0) > 0 && (
        <>
          <div className="metrics-sep" />
          <MetricGroup label="Gemini">
            <MetricItem name="calls"     value={m!.calls.gemini.total} />
            <MetricItem name="ok"        value={m!.calls.gemini.parseOk}   accent="ok" />
            <MetricItem name="parseFail" value={m!.calls.gemini.parseFail} accent={m!.calls.gemini.parseFail > 0 ? "warn" : undefined} />
            <MetricItem name="apiErr"    value={m!.calls.gemini.apiError}  accent={m!.calls.gemini.apiError  > 0 ? "err"  : undefined} />
          </MetricGroup>
        </>
      )}
      <div className="metrics-sep" />
      <MetricGroup label="Latency">
        <MetricItem name="avg"    value={`${avg}ms`} />
        <MetricItem name="max"    value={`${max}ms`} />
        <MetricItem name="tokens" value={(m?.tokens.prompt ?? 0) + (m?.tokens.completion ?? 0)} />
      </MetricGroup>
      <div className="metrics-sep" />
      <MetricGroup label="Topics">
        <MetricItem name="decided"   value={m?.topics.decided   ?? 0} accent={(m?.topics.decided   ?? 0) > 0 ? "ok"  : undefined} />
        <MetricItem name="undecided" value={m?.topics.undecided ?? 0} accent={(m?.topics.undecided ?? 0) > 0 ? "err" : undefined} />
      </MetricGroup>
    </div>
  );
}

function MetricGroup({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="metric-group">
      <span className="metric-group-label">{label}</span>
      <div className="metric-group-items">{children}</div>
    </div>
  );
}

function MetricItem({ name, value, accent }: {
  name: string; value: string | number; accent?: "ok" | "warn" | "err";
}) {
  return (
    <span className="metric">
      {name}<span className={accent ?? ""}> {value}</span>
    </span>
  );
}

// ─── Workspace Editor ─────────────────────────────────────────────

function WorkspaceEditor({ wsState, setWsState, wsLog, addWsLog, clearWsLog }: {
  wsState:    WsEditorState;
  setWsState: React.Dispatch<React.SetStateAction<WsEditorState>>;
  wsLog:      WsLogEntry[];
  addWsLog:   (entry: Omit<WsLogEntry, "id">) => void;
  clearWsLog: () => void;
}) {
  const { workspacePath, files, skipped, selectedFile, original, proposed, proposeSummary, expandedFolders } = wsState;

  // 트랜지언트 UI state — 탭 전환 시 초기화돼도 무방
  const [status,    setStatus]    = useState("");
  const [statusType,setStatusType]= useState<"" | "ok" | "err" | "info">("");
  const [busy,      setBusy]      = useState(false);

  const tree = useMemo(() => buildTree(files), [files]);

  function patch<K extends keyof WsEditorState>(key: K, val: WsEditorState[K]) {
    setWsState(prev => ({ ...prev, [key]: val }));
  }

  function toggleFolder(path: string) {
    setWsState(prev => {
      const next = new Set(prev.expandedFolders);
      next.has(path) ? next.delete(path) : next.add(path);
      return { ...prev, expandedFolders: next };
    });
  }

  function showStatus(msg: string, type: "ok" | "err" | "info" = "info") {
    setStatus(msg); setStatusType(type);
  }

  async function openWorkspace() {
    const res = await window.api.selectWorkspace();
    if (res.canceled) return;
    const wp = res.workspacePath;
    setWsState(prev => ({
      ...prev,
      workspacePath: wp,
      selectedFile: null, original: null, proposed: null, proposeSummary: "",
    }));
    clearWsLog();
    showStatus("스캔 중...", "info");
    setBusy(true);
    const scan = await window.api.scanWorkspace(wp);
    const topLevel = buildTree(scan.files)
      .filter((n): n is FileTreeNode & { type: "folder" } => n.type === "folder")
      .map(n => n.path);
    setWsState(prev => ({
      ...prev,
      files: scan.files,
      skipped: scan.skipped,
      expandedFolders: new Set(topLevel),
    }));
    setBusy(false);
    showStatus(
      `${scan.files.length}개 파일${scan.skipped > 0 ? ` (+${scan.skipped}개 제외)` : ""}`,
      "ok",
    );
  }

  async function selectFile(rel: string) {
    if (!workspacePath) return;
    setWsState(prev => ({ ...prev, selectedFile: rel, original: null, proposed: null, proposeSummary: "" }));
    showStatus("파일 읽는 중...", "info");
    const res = await window.api.readWorkspaceFile(workspacePath, rel);
    if (!res.ok) { showStatus(res.error, "err"); return; }
    patch("original", res.content.replace(/\r\n/g, "\n"));
    showStatus(rel, "ok");
  }

  function proposeEdit() {
    if (!selectedFile || original === null) return;
    const res = mockEdit(selectedFile, original);
    if ("error" in res) { showStatus(res.error, "err"); return; }
    setWsState(prev => ({ ...prev, proposed: res.result, proposeSummary: res.summary }));
    addWsLog({
      type: "file_edit_proposed",
      relativePath: selectedFile,
      summary: res.summary,
      timestamp: new Date().toLocaleTimeString(),
    });
    showStatus(`제안: ${res.summary}`, "info");
  }

  async function applyEdit() {
    if (!workspacePath || !selectedFile || proposed === null) return;
    const confirmed = window.confirm(
      `이 변경을 실제 파일에 적용할까요?\n\n파일: ${selectedFile}\n변경: ${proposeSummary || "수정 제안"}`,
    );
    if (!confirmed) return;
    setBusy(true);
    showStatus("저장 중...", "info");
    const res = await window.api.writeWorkspaceFile(workspacePath, selectedFile, proposed);
    setBusy(false);
    if (!res.ok) { showStatus(res.error, "err"); return; }
    const saved = proposed;
    setWsState(prev => ({ ...prev, original: saved, proposed: null, proposeSummary: "" }));
    addWsLog({
      type: "file_edit_applied",
      relativePath: selectedFile,
      summary: "사용자가 diff 확인 후 변경을 적용함",
      timestamp: new Date().toLocaleTimeString(),
    });
    showStatus(`저장됨: ${selectedFile}`, "ok");
  }

  const diff = useMemo(
    () => original !== null && proposed !== null ? computeDiff(original, proposed) : null,
    [original, proposed],
  );

  const diffStats = useMemo(() => {
    if (!diff) return null;
    return {
      added:     diff.filter(l => l.type === "add").length,
      removed:   diff.filter(l => l.type === "remove").length,
      unchanged: diff.filter(l => l.type === "same").length,
    };
  }, [diff]);

  const noChange = diff !== null && diffStats?.added === 0 && diffStats?.removed === 0;

  return (
    <div className="workspace-editor">
      {/* Toolbar */}
      <div className="ws-toolbar">
        <button onClick={openWorkspace} disabled={busy}>Open Workspace</button>
        <span className="ws-path">
          {workspacePath
            ? workspacePath
            : "폴더를 선택하면 파일 목록이 표시됩니다"}
        </span>
      </div>

      {/* Body */}
      <div className="ws-body">

        {/* File Explorer */}
        <div className="ws-explorer">
          <div className="ws-explorer-title">
            Files
            {files.length > 0 && (
              <span className="ws-file-count">{files.length}</span>
            )}
          </div>
          <div className="ws-file-list">
            {!workspacePath ? (
              <div className="ws-empty-hint">워크스페이스를 먼저 선택하세요</div>
            ) : files.length === 0 ? (
              <div className="ws-empty-hint">파일 없음</div>
            ) : (
              <FileTree
                nodes={tree}
                depth={0}
                expandedFolders={expandedFolders}
                selectedFile={selectedFile}
                busy={busy}
                onToggleFolder={toggleFolder}
                onSelectFile={path => !busy && selectFile(path)}
              />
            )}
            {skipped > 0 && (
              <div className="ws-skipped">+{skipped}개 생략 (제한 초과)</div>
            )}
          </div>
        </div>

        {/* Panels */}
        <div className="ws-panels">

          {/* 원본 */}
          <div className="ws-panel">
            <div className="ws-panel-title">원본</div>
            <div className="ws-panel-body">
              {original === null ? (
                <div className="empty">파일을 선택하세요</div>
              ) : (
                <textarea className="ws-code" readOnly value={original} />
              )}
            </div>
          </div>

          {/* 수정 제안 / diff */}
          <div className="ws-panel">
            <div className="ws-panel-title">수정 제안</div>
            <div className="ws-panel-body">
              {proposed === null ? (
                <div className="empty">
                  {original !== null
                    ? "Mock Edit Proposal 버튼을 누르세요"
                    : "파일을 선택하세요"}
                </div>
              ) : noChange ? (
                <div className="empty">변경 없음 (내용 동일)</div>
              ) : (
                <>
                  <div className="diff-stats-bar">
                    <span className="diff-stat add">+{diffStats!.added} added</span>
                    <span className="diff-stat remove">-{diffStats!.removed} removed</span>
                    <span className="diff-stat same">{diffStats!.unchanged} unchanged</span>
                  </div>
                  <div className="diff-view">
                    {diff!.map((line, i) => (
                      <div key={i} className={`diff-line ${line.type}`}>
                        <span className="diff-sign">
                          {line.type === "add" ? "+" : line.type === "remove" ? "-" : " "}
                        </span>
                        <span className="diff-text">{line.text}</span>
                      </div>
                    ))}
                  </div>
                </>
              )}
            </div>
          </div>

          {/* Edit Log */}
          <div className="ws-log-panel">
            <div className="ws-panel-title">Edit Log</div>
            <div className="ws-panel-body">
              {wsLog.length === 0 ? (
                <div className="empty">기록 없음</div>
              ) : wsLog.map(entry => (
                <div key={entry.id} className="ws-log-entry">
                  <div className={`ws-log-type ${entry.type === "file_edit_proposed" ? "proposed" : "applied"}`}>
                    {entry.type === "file_edit_proposed" ? "제안됨" : "적용됨"}
                  </div>
                  <div className="ws-log-path" title={entry.relativePath}>
                    {entry.relativePath.length > 32
                      ? "…" + entry.relativePath.slice(-29)
                      : entry.relativePath}
                  </div>
                  {entry.type === "file_edit_proposed" && (
                    <div className="ws-log-summary">{entry.summary}</div>
                  )}
                  <div className="ws-log-time">{entry.timestamp}</div>
                </div>
              ))}
            </div>
          </div>

        </div>
      </div>

      {/* Footer */}
      <div className="ws-footer">
        <button
          className="primary"
          onClick={proposeEdit}
          disabled={busy || original === null}
        >
          Mock Edit Proposal
        </button>
        <button
          onClick={applyEdit}
          disabled={busy || proposed === null || noChange}
        >
          Apply
        </button>
        {proposeSummary && <span className="ws-propose-summary">{proposeSummary}</span>}
        <span className={`ws-status ${statusType}`}>{status}</span>
      </div>
    </div>
  );
}

// ─── File Tree Component ──────────────────────────────────────────

function FileTree({ nodes, depth, expandedFolders, selectedFile, busy, onToggleFolder, onSelectFile }: {
  nodes: FileTreeNode[];
  depth: number;
  expandedFolders: Set<string>;
  selectedFile: string | null;
  busy: boolean;
  onToggleFolder: (path: string) => void;
  onSelectFile: (path: string) => void;
}) {
  return (
    <>
      {nodes.map(node =>
        node.type === "folder" ? (
          <div key={node.path}>
            <div
              className="ws-tree-folder"
              style={{ paddingLeft: `${6 + depth * 14}px` }}
              onClick={() => onToggleFolder(node.path)}
              title={node.path}
            >
              <span className="ws-tree-arrow">
                {expandedFolders.has(node.path) ? "▾" : "▸"}
              </span>
              {node.name}
            </div>
            {expandedFolders.has(node.path) && (
              <FileTree
                nodes={node.children}
                depth={depth + 1}
                expandedFolders={expandedFolders}
                selectedFile={selectedFile}
                busy={busy}
                onToggleFolder={onToggleFolder}
                onSelectFile={onSelectFile}
              />
            )}
          </div>
        ) : (
          <div
            key={node.path}
            className={`ws-file-item ${selectedFile === node.path ? "selected" : ""}`}
            style={{ paddingLeft: `${18 + depth * 14}px` }}
            onClick={() => !busy && onSelectFile(node.path)}
            title={node.path}
          >
            {node.name}
          </div>
        )
      )}
    </>
  );
}
